version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - back_net

  web:
    build:
      context: .
      target: final
    container_name: flask_app
    environment:
      DATABASE_URL: postgresql://user:pass@db:5432/db
    depends_on:
      - db
      - seed_runner
    networks:
      - front_net
      - back_net
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - web
    networks:
      - front_net
  
  seed_runner:
    build:
      context: .
      dockerfile: Dockerfile.seed
    container_name: seed_runner
    environment:
      DATABASE_URL: postgresql://user:pass@db:5432/db
    volumes:
      - seed_output:/app/seed/output
    networks:
      - back_net
    restart: "no"
networks:
  front_net:
  back_net:

volumes:
  postgres_data:
  nginx_logs:
  seed_output: